# Generated by Django 4.1.7 on 2023-06-10 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
