# Generated by Django 4.1.7 on 2023-06-11 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_app", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankForm",
        ),
        migrations.DeleteModel(
            name="Material",
        ),
    ]
